// <auto-generated />
using System;
using EcoTrack.WebMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTrack.WebMvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250925003706_NameOfYourRecentChange")]
    partial class NameOfYourRecentChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EcoTrack.WebMvc.Models.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CarbonEmission")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");

                    b.HasDiscriminator<int>("ActivityType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.Badge", b =>
                {
                    b.Property<Guid>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaMet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEarned")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("BadgeId");

                    b.HasIndex("UserId");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.EmissionFactor", b =>
                {
                    b.Property<Guid>("EmissionFactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("EmissionFactorId");

                    b.ToTable("EmissionFactors");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.Family", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedConsumption")
                        .HasColumnType("TEXT");

                    b.HasKey("FamilyId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.LeaderboardEntry", b =>
                {
                    b.Property<int>("LeaderboardEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CarbonEmission")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LeaderboardEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.Suggestion", b =>
                {
                    b.Property<Guid>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeIssued")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SavingAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("SuggestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectedAccounts")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LifestylePreferences")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.ApplianceActivity", b =>
                {
                    b.HasBaseType("EcoTrack.WebMvc.Models.Activity");

                    b.Property<string>("ApplianceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmissionFactorId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PowerRating")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UsageTime")
                        .HasColumnType("decimal(18, 2)");

                    b.HasIndex("EmissionFactorId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.ElectricityActivity", b =>
                {
                    b.HasBaseType("EcoTrack.WebMvc.Models.Activity");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("EmissionFactorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasIndex("EmissionFactorId");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("EmissionFactorId")
                                .HasColumnName("ElectricityActivity_EmissionFactorId");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.FoodActivity", b =>
                {
                    b.HasBaseType("EcoTrack.WebMvc.Models.Activity");

                    b.Property<Guid>("EmissionFactorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasIndex("EmissionFactorId");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("EmissionFactorId")
                                .HasColumnName("FoodActivity_EmissionFactorId");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.TravelActivity", b =>
                {
                    b.HasBaseType("EcoTrack.WebMvc.Models.Activity");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("EmissionFactorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationEnd")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationStart")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasIndex("EmissionFactorId");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("EmissionFactorId")
                                .HasColumnName("TravelActivity_EmissionFactorId");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.WasteActivity", b =>
                {
                    b.HasBaseType("EcoTrack.WebMvc.Models.Activity");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("EmissionFactorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasIndex("EmissionFactorId");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("EmissionFactorId")
                                .HasColumnName("WasteActivity_EmissionFactorId");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.Activity", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.Badge", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.LeaderboardEntry", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.Suggestion", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.User", "User")
                        .WithMany("Suggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.User", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.ApplianceActivity", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.EmissionFactor", "EmissionFactor")
                        .WithMany()
                        .HasForeignKey("EmissionFactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmissionFactor");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.ElectricityActivity", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.EmissionFactor", "EmissionFactor")
                        .WithMany()
                        .HasForeignKey("EmissionFactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmissionFactor");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.FoodActivity", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.EmissionFactor", "EmissionFactor")
                        .WithMany()
                        .HasForeignKey("EmissionFactorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmissionFactor");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.TravelActivity", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.EmissionFactor", "EmissionFactor")
                        .WithMany()
                        .HasForeignKey("EmissionFactorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmissionFactor");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.WasteActivity", b =>
                {
                    b.HasOne("EcoTrack.WebMvc.Models.EmissionFactor", "EmissionFactor")
                        .WithMany()
                        .HasForeignKey("EmissionFactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmissionFactor");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.Family", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("EcoTrack.WebMvc.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Badges");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
